path:
  raw:       "/mnt/e/mlgo-data/raw"
  processed: "/mnt/e/mlgo-data/processed"
  final:     "/mnt/e/mlgo-data/final"
  temp:      "/mnt/e/mlgo-data/.temp"
  logs:      "./logs"

split:
  val: 0.2
  test:  0.2

seed: 69

species:
  name:    "mmusculus"
  short:   "mm"
  ensembl: "mmusculus_gene_ensembl"
