datadir: "/mnt/e/mlgo-data"
scripts:
  downloadgse.py:
    query: "Classes == 2 & Platform == 'GPL570'"
  enrichment.R:
    datasets: "data/raw/datasets.txt"
    datadir: "data/raw"
    include_genes: "data/raw/landmark.txt"
