path:
  raw:       "./data/raw"
  processed: "./data/processed"
  final:     "./data/final"
  temp:      "./data/.temp"
  logs:      "./logs"

split:
  val: 0.2
  test:  0.2

seed: 69

species:
  name:    "mmusculus"
  short:   "mm"
  ensembl: "mmusculus_gene_ensembl"
