path:
  raw:       "/home/ubuntu/mlgo-data/raw"
  processed: "/home/ubuntu/mlgo-data/processed"
  final:     "/home/ubuntu/mlgo-data/final"
  temp:      "/home/ubuntu/mlgo-data/.temp"
  logs:      "/home/ubuntu/mlgo-data/logs"

split:
  val: 0.2
  test:  0.2

seed: 69

species:
  name:    "mmusculus"
  short:   "mm"
  ensembl: "mmusculus_gene_ensembl"
