project:
  output-dir: rendered

author: Tony Kabilan Okeke

format:
    revealjs:
        incremental: true
        theme: [night, custom.scss]
        footer: BMES 547 Project
        slide-number: c
        show-slide-number: all
        background-transition: fade
