project:
  output-dir: rendered

author: Tony Kabilan Okeke

format:
    revealjs:
        incremental: true
        theme: [serif, custom.scss]
        slide-number: c
        show-slide-number: all
        background-transition: fade
